baseURL = 'https://guoquanle.github.io/'
languageCode = 'en'
# languageCode = 'zh-CN'
theme = "JuiceBar"
title = "guoquanle's blog"

[params]
author = "hotjuicew"
description = "My site description"
authorImage = "/images/profile.jpg"
paginate = 5

Title = "天地一沙鸥"
content = "I'm guoquanle, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/astronaut.jpeg"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "Github"
url = "https://github.com/hotjuicew"
[[params.social]]
name = "telegram"
url = "https://t.me/Hotjuice"
[[params.social]]
name = "twitter"
url = "https://twitter.com/hotjuicee"
[[params.social]]
name = "email"
url = "guoquanle@outlook.com"


[taxonomies]
category = "categories"

# To add a new navigation link
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]



